Update UI for windows
dheerajpv/multiserver pull request #2
Opened 2021-12-28 15:35 UTC by cursorsdottsx

Mainly added more space between form inputs since the animation when an input required space above the input

Moved settings icon to the bottom left, removed text

Flexbox for making the version and type selection more fluid

Fixed typos on file names

2021-12-28 22:56 UTC, dheerajpv commented
There is a small but *very annoying* scrollbar in the new instance window:
![image](https://user-images.githubusercontent.com/57048370/147612523-a45d494d-fa8f-4e29-8a47-e44fc4b987b4.png)

Other than that, it looks good to merge!

2021-12-28 23:01 UTC, dheerajpv requested changes
Other than that one issue, this PR is good to go

2021-12-28 23:01 UTC, dheerajpv commented on src/windows/NewInstanceWindow.tsx
> +                className="flex container flex-col gap-4"
This gap is probably too large and creates a scrollbar on the window.
```suggestion
                className="flex container flex-col gap-3"
```

2021-12-29 18:52 UTC, cursorsdottsx commented
Ok it looks like it worked (on my machine). I have committed the new suggestion.

2021-12-29 18:58 UTC, dheerajpv approved these changes
Looks good!

2021-12-29 18:58 UTC, merged